import { parseJson } from "./src/main/minimax/minimax-parsing.js";
const tool1 = `patch:[{"op":"replace","path":"/basicInfo/subtitle","value":"tool 拼接噪声A"],questions:[`;
const tool2 = `reply:'工具参数拼接可恢复',patch:[{'op':'replace','path':'/basicInfo/subtitle','value':'太原工具参数'},questions:['是否确认接驳时间？']`;
const onlyPatch1 = `patch:[{"op":"replace","path":"/basicInfo/subtitle","value":"tool 拼接噪声A"],questions:[`;
const onlyPatch2 = `patch:[{'op':'replace','path':'/basicInfo/subtitle','value':'太原工具参数'},questions:['是否确认接驳时间？']`;
const patched2 = `reply:'工具参数拼接可恢复',patch:[{"op":"replace","path":"/basicInfo/subtitle","value":"太原工具参数"},questions:['是否确认接驳时间？']`;
console.log('tool1', parseJson(tool1));
console.log('tool2', parseJson(tool2));
console.log('only2', parseJson(onlyPatch2));
console.log('patched2', parseJson(patched2));
