import assert from "node:assert/strict";
import test from "node:test";
import { mkdir } from "node:fs/promises";
import { createServer } from "vite";
import react from "@vitejs/plugin-react";
import { chromium } from "playwright";

test("紧凑双行：阶段、任务详情、异常、JSON 和窄屏可用", async () => {
  const server = await createServer({ configFile: false, root: process.cwd(), plugins: [react()], server: { host: "127.0.0.1", port: 0 }, logLevel: "error" });
  await server.listen();
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.goto(`${server.resolvedUrls!.local[0]}test/fixtures/stage-nav-ui/index.html`);
    await page.getByRole("tab", { name: "方案审查", exact: true }).waitFor();
    assert.equal(await page.locator("#workflow-task-status").count(), 1);
    assert.equal(await page.getByText("草稿已保存 · 未发布", { exact: true }).isVisible(), true);
    assert.equal(await page.getByRole("progressbar").count(), 0);
    const details = page.locator("details");
    assert.equal(await details.evaluate(node => (node as HTMLDetailsElement).open), false);
    const usageMetric = page.getByLabel("当前产品累计 AI 消耗");
    assert.equal(await usageMetric.isVisible(), true);
    assert.match(await usageMetric.innerText(), /1\.5k Token\s*· 约 ¥0\.12/);
    const title = page.getByText("方案协作", { exact: true });
    assert.ok((await title.locator("..").boundingBox())!.y <= 90, "正文标题栏应紧接全局顶栏与 44px 阶段栏");
    assert.equal(await page.getByLabel("方案就绪状态").count(), 0, "全局顶栏不重复展示就绪度胶囊");
    await page.getByRole("button", { name: "查看 JSON", exact: true }).click();
    await page.getByText("JSON 产品数据", { exact: true }).waitFor();
    await page.getByRole("button", { name: "返回卡片", exact: true }).click();
    await page.locator("summary").click();
    assert.equal(await page.getByText(/当前产品累计 1.5k/).isVisible(), true);
    assert.equal(await page.getByRole("progressbar").count(), 0, "完成状态不展示冗余进度条");
    await page.locator("summary").click();
    await page.getByRole("tab", { name: "VBK 录入", exact: true }).click();
    assert.equal(await page.getByText("VBK 浏览器", { exact: true }).isVisible(), true);
    await page.evaluate(() => (window as any).stageFixture.setStatus("running"));
    await page.getByRole("progressbar", { name: "后台任务进度" }).waitFor();
    assert.equal(await page.getByRole("progressbar").getAttribute("aria-valuenow"), "42");
    await page.evaluate(() => (window as any).stageFixture.setStatus("failed"));
    await page.locator("#workflow-task-status").getByText("后台任务执行失败", { exact: true }).waitFor();
    assert.equal(await details.evaluate(node => (node as HTMLDetailsElement).open), false, "任务失败不自动展开详情");
    await page.locator("summary").click();
    await page.getByText("资源核验失败，请补充景点信息后继续。", { exact: true }).waitFor();
    assert.equal(await details.evaluate(node => (node as HTMLDetailsElement).open), true);
    await page.locator("summary").click();
    await page.evaluate(() => (window as any).stageFixture.setStatus("needs_attention"));
    await page.locator("#workflow-task-status").getByText("后台任务等待处理", { exact: true }).waitFor();
    assert.equal(await details.evaluate(node => (node as HTMLDetailsElement).open), false, "等待处理不自动展开详情");
    await page.evaluate(() => { (window as any).stageFixture.setStatus("succeeded"); (window as any).stageFixture.setSaved(false); });
    assert.equal(await page.getByText("草稿已保存 · 未发布", { exact: true }).count(), 0, "任务完成不代表草稿保存");
    await page.evaluate(() => (window as any).stageFixture.setReady(false));
    await page.getByText("2 项待处理", { exact: true }).waitFor();
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    assert.equal(await page.locator("summary").isVisible(), true);
    assert.equal(await usageMetric.isVisible(), true);
    await page.locator("summary").focus();
    await page.keyboard.press("Enter");
    assert.equal(await details.evaluate(node => (node as HTMLDetailsElement).open), true);
    assert.ok((await page.locator("#workflow-task-status").boundingBox())!.y < (await page.locator("#workflow-task-details-status").boundingBox())!.y, "展开详情时摘要保持在详情上方");
    await mkdir("output/playwright/stage-nav", { recursive: true });
    await page.screenshot({ path: "output/playwright/stage-nav/narrow.png", fullPage: true });
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.locator("summary").click();
    await page.getByRole("tab", { name: /^方案审查/ }).click();
    await page.screenshot({ path: "output/playwright/stage-nav/desktop.png", fullPage: true });
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await server.close(); }
});
